from datetime import datetime, timedelta, timezone

import pytest

from struct_gen.generated_file import generated_file_banner


def test_generated_file_banner_uses_source_name_and_utc_timestamp() -> None:
    generated_at = datetime(
        2026, 7, 3, 10, 9, 10, tzinfo=timezone(timedelta(hours=2))
    )

    assert generated_file_banner("example.ndef", generated_at) == (
        "// This file was generated by struct-gen.\n"
        "// Source: example.ndef\n"
        "// Generated: 2026-07-03T08:09:10Z\n"
        "// Do not modify this file directly; regenerate it from the source definition.\n\n"
    )


def test_generated_file_banner_rejects_timestamp_without_timezone() -> None:
    with pytest.raises(ValueError, match="must include a timezone"):
        generated_file_banner("example.ndef", datetime(2026, 7, 3, 8, 9, 10))
