from pathlib import Path

from silwright.generated_file import (
    GeneratedFile,
    generated_file_banner,
    render_generated_file,
    write_generated_file,
    write_generated_files,
)


def test_generated_file_banner_uses_source_name_and_tool_version() -> None:
    assert generated_file_banner("example.ndef", "1.2.3") == (
        "// This file was generated by Silwright 1.2.3.\n"
        "// Source: example.ndef\n"
        "// Do not modify this file directly; regenerate it from the source definition.\n\n"
    )


def test_write_generated_file_skips_unchanged_content(tmp_path: Path) -> None:
    definition = tmp_path / "example.ndef"
    target = tmp_path / "example.hpp"
    definition.write_text("module example\n")
    content = "#pragma once\n"

    write_generated_file(target, content, definition)
    original_mtime = target.stat().st_mtime_ns

    write_generated_file(target, content, definition)

    assert target.stat().st_mtime_ns == original_mtime


def test_write_generated_files_replaces_changed_outputs(tmp_path: Path) -> None:
    definition = tmp_path / "example.ndef"
    definition.write_text("module example\n")
    first = tmp_path / "example.hpp"
    second = tmp_path / "example.cpp"

    paths = write_generated_files(
        (
            GeneratedFile(first, "#pragma once\n"),
            GeneratedFile(second, '#include "example.hpp"\n'),
        ),
        definition,
        tool_version="1.2.3",
    )

    assert paths == (first, second)
    assert first.read_text() == render_generated_file(
        "#pragma once\n", definition, tool_version="1.2.3"
    )
    assert second.read_text() == render_generated_file(
        '#include "example.hpp"\n', definition, tool_version="1.2.3"
    )
