"""Common metadata and writing support for generated files."""

from datetime import UTC, datetime
from pathlib import Path


def generated_file_banner(source_name: str, generated_at: datetime) -> str:
    """Render the comment placed at the beginning of every generated file."""
    if generated_at.tzinfo is None:
        raise ValueError("generation timestamp must include a timezone")
    timestamp = generated_at.astimezone(UTC).isoformat(timespec="seconds").replace(
        "+00:00", "Z"
    )
    return (
        "// This file was generated by struct-gen.\n"
        f"// Source: {source_name}\n"
        f"// Generated: {timestamp}\n"
        "// Do not modify this file directly; regenerate it from the source definition.\n\n"
    )


def write_generated_file(
    path: Path,
    content: str,
    definition_path: Path,
    generated_at: datetime | None = None,
) -> None:
    """Write generated content with source and generation metadata."""
    timestamp = generated_at if generated_at is not None else datetime.now(UTC)
    rendered = generated_file_banner(definition_path.name, timestamp) + content
    path.write_text(rendered, encoding="utf-8", newline="\n")
