"""Common metadata and writing support for generated files."""

from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from tempfile import NamedTemporaryFile


@dataclass(frozen=True, slots=True)
class GeneratedFile:
    """A generated output target and its content without the file banner."""

    path: Path
    content: str


def generated_file_banner(source_name: str, tool_version: str | None = None) -> str:
    """Render the comment placed at the beginning of every generated file."""
    tool = "Silwright"
    resolved_version = _silwright_version() if tool_version is None else tool_version
    if resolved_version is not None:
        tool = f"{tool} {resolved_version}"
    return (
        f"// This file was generated by {tool}.\n"
        f"// Source: {source_name}\n"
        "// Do not modify this file directly; regenerate it from the source definition.\n\n"
    )


def render_generated_file(
    content: str, definition_path: Path, tool_version: str | None = None
) -> str:
    """Render generated content with stable source and tool metadata."""
    return generated_file_banner(definition_path.name, tool_version) + content


def write_generated_file(
    path: Path,
    content: str,
    definition_path: Path,
    generated_at: object | None = None,
) -> None:
    """Write one generated file through the batch writer.

    The generated_at parameter is accepted for compatibility with older callers; generated
    content no longer embeds generation timestamps.
    """
    write_generated_files((GeneratedFile(path, content),), definition_path)


def write_generated_files(
    files: tuple[GeneratedFile, ...],
    definition_path: Path,
    tool_version: str | None = None,
) -> tuple[Path, ...]:
    """Write generated files after preparing all changed outputs as temporary files."""
    rendered = tuple(
        GeneratedFile(item.path, render_generated_file(item.content, definition_path, tool_version))
        for item in files
    )
    changed = tuple(item for item in rendered if _read_existing(item.path) != item.content)
    temporary_paths: list[Path] = []
    try:
        for item in changed:
            item.path.parent.mkdir(parents=True, exist_ok=True)
            with NamedTemporaryFile(
                "w",
                encoding="utf-8",
                newline="\n",
                dir=item.path.parent,
                prefix=f".{item.path.name}.",
                suffix=".tmp",
                delete=False,
            ) as temporary:
                temporary.write(item.content)
                temporary_paths.append(Path(temporary.name))
        for item, temporary_path in zip(changed, temporary_paths, strict=True):
            temporary_path.replace(item.path)
    finally:
        for temporary_path in temporary_paths:
            if temporary_path.exists():
                temporary_path.unlink()
    return tuple(item.path for item in files)


def _read_existing(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def _silwright_version() -> str | None:
    try:
        return version("silwright")
    except PackageNotFoundError:
        return None
