// This file was generated by Silwright.
// Source: simple_lang.ndef
// Generated: 2026-07-06T13:52:17Z
// Do not modify this file directly; regenerate it from the source definition.

#include "simple_lang.hpp"
