// This file was generated by Silwright.
// Source: simple_lang.ndef
// Generated: 2026-07-09T15:08:28Z
// Do not modify this file directly; regenerate it from the source definition.

#include "simple_lang_transformer.hpp"

#include <cassert>
#include <type_traits>
#include <utility>
#include <variant>

namespace lir {

expr_list transformer::rewrite(std::unique_ptr<expr> node) {
    if (!node) {
        return {};
    }
    return std::visit([this] (auto& alternative) -> expr_list {
        using alternative_type = std::decay_t<decltype(alternative)>;
        auto replacements = rewrite(
            std::make_unique<alternative_type>(std::move(alternative)));
        expr_list result;
        for (auto& replacement : replacements) {
            if (replacement) {
                if constexpr (std::is_same_v<
                    typename std::decay_t<decltype(replacement)>::element_type,
                    expr>) {
                    result.push_back(std::move(replacement));
                } else {
                    result.push_back(std::make_unique<expr>(std::move(*replacement)));
                }
            }
        }
        return result;
    }, *node);
}

expr_list transformer::rewrite(std::unique_ptr<number> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<char_literal> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<bool_literal> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<string_literal> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<allocate_record_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<store_record_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<load_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<store_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<if_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<while_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<function_call> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<cast_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<discard_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<return_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<break_statement> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<unary_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

expr_list transformer::rewrite(std::unique_ptr<binary_expression> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

std::vector<std::unique_ptr<function_definition>> transformer::rewrite(std::unique_ptr<function_definition> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

std::vector<std::unique_ptr<import_definition>> transformer::rewrite(std::unique_ptr<import_definition> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

std::vector<std::unique_ptr<global_definition>> transformer::rewrite(std::unique_ptr<global_definition> node) {
    if (!node) {
        return {};
    }
    rewrite_children(*node);
    return visit_multiple(*node);
}

std::unique_ptr<module> transformer::rewrite(std::unique_ptr<module> node) {
    if (!node) {
        return nullptr;
    }
    rewrite_children(*node);
    return visit_single(*node);
}

void transformer::rewrite_children(number& value) {
    (void)value;
}

void transformer::rewrite_children(char_literal& value) {
    (void)value;
}

void transformer::rewrite_children(bool_literal& value) {
    (void)value;
}

void transformer::rewrite_children(string_literal& value) {
    (void)value;
}

void transformer::rewrite_children(allocate_record_expression& value) {
    (void)value;
}

void transformer::rewrite_children(store_record_expression& value) {
    (void)value;
}

void transformer::rewrite_children(load_expression& value) {
    (void)value;
}

void transformer::rewrite_children(store_expression& value) {
    auto replacement_value = rewrite(std::move(value.value));
    assert(replacement_value.size() <= 1);
    if (replacement_value.empty()) {
        value.value = nullptr;
    } else {
        value.value = std::move(replacement_value.front());
    }
}

void transformer::rewrite_children(if_expression& value) {
    auto replacement_condition = rewrite(std::move(value.condition));
    assert(replacement_condition.size() <= 1);
    if (replacement_condition.empty()) {
        value.condition = nullptr;
    } else {
        value.condition = std::move(replacement_condition.front());
    }
    expr_list replacement_then_code;
    for (auto& child : value.then_code) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_then_code.push_back(std::move(replacement));
            }
        }
    }
    value.then_code = std::move(replacement_then_code);
    expr_list replacement_else_code;
    for (auto& child : value.else_code) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_else_code.push_back(std::move(replacement));
            }
        }
    }
    value.else_code = std::move(replacement_else_code);
}

void transformer::rewrite_children(while_expression& value) {
    auto replacement_condition = rewrite(std::move(value.condition));
    assert(replacement_condition.size() <= 1);
    if (replacement_condition.empty()) {
        value.condition = nullptr;
    } else {
        value.condition = std::move(replacement_condition.front());
    }
    expr_list replacement_while_code;
    for (auto& child : value.while_code) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_while_code.push_back(std::move(replacement));
            }
        }
    }
    value.while_code = std::move(replacement_while_code);
}

void transformer::rewrite_children(function_call& value) {
    expr_list replacement_arguments;
    for (auto& child : value.arguments) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_arguments.push_back(std::move(replacement));
            }
        }
    }
    value.arguments = std::move(replacement_arguments);
}

void transformer::rewrite_children(cast_expression& value) {
    auto replacement_expression = rewrite(std::move(value.expression));
    assert(replacement_expression.size() <= 1);
    if (replacement_expression.empty()) {
        value.expression = nullptr;
    } else {
        value.expression = std::move(replacement_expression.front());
    }
}

void transformer::rewrite_children(discard_expression& value) {
    auto replacement_expression = rewrite(std::move(value.expression));
    assert(replacement_expression.size() <= 1);
    if (replacement_expression.empty()) {
        value.expression = nullptr;
    } else {
        value.expression = std::move(replacement_expression.front());
    }
}

void transformer::rewrite_children(return_expression& value) {
    auto replacement_expression = rewrite(std::move(value.expression));
    assert(replacement_expression.size() <= 1);
    if (replacement_expression.empty()) {
        value.expression = nullptr;
    } else {
        value.expression = std::move(replacement_expression.front());
    }
}

void transformer::rewrite_children(break_statement& value) {
    (void)value;
}

void transformer::rewrite_children(unary_expression& value) {
    auto replacement_expr = rewrite(std::move(value.expr));
    assert(replacement_expr.size() <= 1);
    if (replacement_expr.empty()) {
        value.expr = nullptr;
    } else {
        value.expr = std::move(replacement_expr.front());
    }
}

void transformer::rewrite_children(binary_expression& value) {
    auto replacement_left = rewrite(std::move(value.left));
    assert(replacement_left.size() <= 1);
    if (replacement_left.empty()) {
        value.left = nullptr;
    } else {
        value.left = std::move(replacement_left.front());
    }
    auto replacement_right = rewrite(std::move(value.right));
    assert(replacement_right.size() <= 1);
    if (replacement_right.empty()) {
        value.right = nullptr;
    } else {
        value.right = std::move(replacement_right.front());
    }
}

void transformer::rewrite_children(function_definition& value) {
    expr_list replacement_code;
    for (auto& child : value.code) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_code.push_back(std::move(replacement));
            }
        }
    }
    value.code = std::move(replacement_code);
}

void transformer::rewrite_children(import_definition& value) {
    (void)value;
}

void transformer::rewrite_children(global_definition& value) {
    (void)value;
}

void transformer::rewrite_children(module& value) {
    std::vector<std::unique_ptr<import_definition>> replacement_imports;
    for (auto& child : value.imports) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_imports.push_back(std::move(replacement));
            }
        }
    }
    value.imports = std::move(replacement_imports);
    std::vector<std::unique_ptr<global_definition>> replacement_globals;
    for (auto& child : value.globals) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_globals.push_back(std::move(replacement));
            }
        }
    }
    value.globals = std::move(replacement_globals);
    std::vector<std::unique_ptr<function_definition>> replacement_functions;
    for (auto& child : value.functions) {
        auto replacements = rewrite(std::move(child));
        for (auto& replacement : replacements) {
            if (replacement) {
                replacement_functions.push_back(std::move(replacement));
            }
        }
    }
    value.functions = std::move(replacement_functions);
}

expr_list transformer::visit_multiple(number& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(char_literal& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(bool_literal& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(string_literal& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(allocate_record_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(store_record_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(load_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(store_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(if_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(while_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(function_call& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(cast_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(discard_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(return_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(break_statement& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(unary_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

expr_list transformer::visit_multiple(binary_expression& value) {
    expr_list result;
    result.push_back(std::make_unique<expr>(std::move(value)));
    return result;
}

std::vector<std::unique_ptr<function_definition>> transformer::visit_multiple(function_definition& value) {
    std::vector<std::unique_ptr<function_definition>> result;
    result.push_back(std::make_unique<function_definition>(std::move(value)));
    return result;
}

std::vector<std::unique_ptr<import_definition>> transformer::visit_multiple(import_definition& value) {
    std::vector<std::unique_ptr<import_definition>> result;
    result.push_back(std::make_unique<import_definition>(std::move(value)));
    return result;
}

std::vector<std::unique_ptr<global_definition>> transformer::visit_multiple(global_definition& value) {
    std::vector<std::unique_ptr<global_definition>> result;
    result.push_back(std::make_unique<global_definition>(std::move(value)));
    return result;
}

std::unique_ptr<module> transformer::visit_single(module& value) {
    return std::make_unique<module>(std::move(value));
}

}  // namespace lir
