// This file was generated by Silwright 0.5.0.
// Source: simple_lang.ndef
// Do not modify this file directly; regenerate it from the source definition.

#pragma once

#include "simple_lang.hpp"

namespace lir {

class transformer {
public:
    virtual ~transformer() = default;

    expr_list rewrite(std::unique_ptr<number> node);
    expr_list rewrite(std::unique_ptr<char_literal> node);
    expr_list rewrite(std::unique_ptr<bool_literal> node);
    expr_list rewrite(std::unique_ptr<string_literal> node);
    expr_list rewrite(std::unique_ptr<allocate_record_expression> node);
    expr_list rewrite(std::unique_ptr<store_record_expression> node);
    expr_list rewrite(std::unique_ptr<load_expression> node);
    expr_list rewrite(std::unique_ptr<store_expression> node);
    expr_list rewrite(std::unique_ptr<if_expression> node);
    expr_list rewrite(std::unique_ptr<while_expression> node);
    expr_list rewrite(std::unique_ptr<function_call> node);
    expr_list rewrite(std::unique_ptr<cast_expression> node);
    expr_list rewrite(std::unique_ptr<discard_expression> node);
    expr_list rewrite(std::unique_ptr<return_expression> node);
    expr_list rewrite(std::unique_ptr<break_statement> node);
    expr_list rewrite(std::unique_ptr<unary_expression> node);
    expr_list rewrite(std::unique_ptr<binary_expression> node);
    expr_list rewrite(std::unique_ptr<expr> node);
    std::vector<std::unique_ptr<function_definition>> rewrite(std::unique_ptr<function_definition> node);
    std::vector<std::unique_ptr<import_definition>> rewrite(std::unique_ptr<import_definition> node);
    std::vector<std::unique_ptr<global_definition>> rewrite(std::unique_ptr<global_definition> node);
    std::unique_ptr<module> rewrite(std::unique_ptr<module> node);

protected:
    virtual expr_list visit_multiple(number& value);
    virtual expr_list visit_multiple(char_literal& value);
    virtual expr_list visit_multiple(bool_literal& value);
    virtual expr_list visit_multiple(string_literal& value);
    virtual expr_list visit_multiple(allocate_record_expression& value);
    virtual expr_list visit_multiple(store_record_expression& value);
    virtual expr_list visit_multiple(load_expression& value);
    virtual expr_list visit_multiple(store_expression& value);
    virtual expr_list visit_multiple(if_expression& value);
    virtual expr_list visit_multiple(while_expression& value);
    virtual expr_list visit_multiple(function_call& value);
    virtual expr_list visit_multiple(cast_expression& value);
    virtual expr_list visit_multiple(discard_expression& value);
    virtual expr_list visit_multiple(return_expression& value);
    virtual expr_list visit_multiple(break_statement& value);
    virtual expr_list visit_multiple(unary_expression& value);
    virtual expr_list visit_multiple(binary_expression& value);
    virtual std::vector<std::unique_ptr<function_definition>> visit_multiple(function_definition& value);
    virtual std::vector<std::unique_ptr<import_definition>> visit_multiple(import_definition& value);
    virtual std::vector<std::unique_ptr<global_definition>> visit_multiple(global_definition& value);
    virtual std::unique_ptr<module> visit_single(module& value);

private:
    void rewrite_children(number& value);
    void rewrite_children(char_literal& value);
    void rewrite_children(bool_literal& value);
    void rewrite_children(string_literal& value);
    void rewrite_children(allocate_record_expression& value);
    void rewrite_children(store_record_expression& value);
    void rewrite_children(load_expression& value);
    void rewrite_children(store_expression& value);
    void rewrite_children(if_expression& value);
    void rewrite_children(while_expression& value);
    void rewrite_children(function_call& value);
    void rewrite_children(cast_expression& value);
    void rewrite_children(discard_expression& value);
    void rewrite_children(return_expression& value);
    void rewrite_children(break_statement& value);
    void rewrite_children(unary_expression& value);
    void rewrite_children(binary_expression& value);
    void rewrite_children(function_definition& value);
    void rewrite_children(import_definition& value);
    void rewrite_children(global_definition& value);
    void rewrite_children(module& value);
};

}  // namespace lir
