// This file was generated by struct-gen.
// Source: simple_lang.ndef
// Generated: 2026-07-03T11:22:37Z
// Do not modify this file directly; regenerate it from the source definition.

#include "simple_lang_dump.hpp"
